version: '3.4'

services:
  html:
    build:
      context: .
      dockerfile: Dockerfile.asciidoctor
    volumes:
      - ./doc:/workdir
    command: asciidoctor -n sdms_dmp.adoc

  pdf:
    build:
      context: .
      dockerfile: Dockerfile.asciidoctor
    volumes:
      - ./doc:/workdir
    command: asciidoctor-pdf -a pdf-themesdir=./ -a pdf-theme=sdms -n sdms_dmp.adoc
